version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    registries:
      - test-pypi
    insecure-external-code-execution: allow
    schedule:
      interval: "daily"

registries:
  test-pypi:
    type: python-index
    url: test.swelljoe.com/simple
    username: ${{secrets.PYPI_USERNAME}}
    password: ${{secrets.PYPI_PASSWORD}}
    replaces-base: true
